# Generated by Django 4.0.5 on 2022-06-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_alter_producto_categoria_alter_producto_idproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('idFoto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreFoto', models.CharField(max_length=100)),
                ('nombreArchivo', models.CharField(max_length=256)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
    ]
