# Generated by Django 4.0.5 on 2022-07-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
